"use client";
import { useEffect, useState } from "react";
import { Activity, ArrowDown, Check, Copy, Gauge, Globe2, RefreshCw, ShieldCheck, Zap } from "lucide-react";

type Status = { activeProxies:number; targetStock:number; status:string; lastMaintenance?:string; nextMaintenance?:string; protocols:Record<string,number>; countries:{code:string;name:string;count:number}[] };
type ProxyItem = { id:string; ip:string; port:number; protocol:string; countryCode?:string; latencyMs?:number; lastCheckedAt?:string; brVerified?:boolean };
const fallback: Status = { activeProxies:0,targetStock:500,status:"INITIALIZING",protocols:{http:0,https:0,socks4:0,socks5:0},countries:[] };

export default function Home() {
  const [status,setStatus]=useState(fallback); const [items,setItems]=useState<ProxyItem[]>([]); const [loading,setLoading]=useState(false); const [copied,setCopied]=useState(""); const [searched,setSearched]=useState(false); const [loadError,setLoadError]=useState("");
  const [country,setCountry]=useState(""); const [protocol,setProtocol]=useState(""); const [limit,setLimit]=useState("5"); const [quality,setQuality]=useState("ALL"); const [withProtocol,setWithProtocol]=useState(false);
  useEffect(()=>{const load=()=>fetch("/api/status",{cache:"no-store"}).then(r=>r.ok?r.json():fallback).then(setStatus).catch(()=>{});void load();const timer=setInterval(load,60_000);return()=>clearInterval(timer)},[]);
  const address=(p:ProxyItem)=>`${withProtocol?p.protocol.toLowerCase()+"://":""}${p.ip}:${p.port}`;
  const generate=async()=>{setLoading(true);setItems([]);setLoadError("");setSearched(true); const q=new URLSearchParams({limit,quality,...(country&&{country}),...(protocol&&{protocol})}); try{const r=await fetch(`/api/proxies?${q}`,{cache:"no-store"});if(!r.ok)throw new Error();const d=await r.json();setItems(d.proxies??[]);}catch{setLoadError("Não foi possível consultar a rede agora. Tente novamente.")}finally{setLoading(false)}};
  const copy=async(text:string,key:string)=>{await navigator.clipboard.writeText(text);setCopied(key);setTimeout(()=>setCopied(""),1800)};
  const fmt=(v?:string)=>v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"Aguardando primeiro ciclo";
  return <main>
    <header className="header"><a className="brand" href="#top"><span>FACTOR</span><b>X</b><i>{"// PROXYS"}</i></a><nav><a href="#generator">Gerador</a><a href="#network">Rede</a><a href="#how">Como funciona</a></nav><a className="button compact" href="#generator">GERAR PROXY</a></header>
    <section className="hero" id="top"><div className="grid-bg"/><div className="x-mark" aria-hidden="true"><i/><i/></div><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> FACTORX NETWORK {status.status}</div><h1>PROXYS QUE<br/><em>FUNCIONAM.</em></h1><p>Sem perder tempo testando. A FactorX verifica e mantém uma pool de proxies públicas ativas para você gerar em segundos.</p><div className="actions"><a className="button" href="#generator">GERAR PROXY <Zap size={16}/></a><a className="button ghost" href="#network">VER STATUS DA REDE</a></div></div><div className="hero-stats"><Stat value={`${status.activeProxies} / ${status.targetStock}`} label="PROXYS NO ESTOQUE"/><Stat value="24H" label="CICLO DE VERIFICAÇÃO"/><Stat value="4" label="PROTOCOLOS"/><Stat value="AUTO" label="REPOSIÇÃO"/></div><a className="scroll" href="#generator">EXPLORE <ArrowDown size={15}/></a></section>
    <section className="section generator" id="generator"><div className="section-tag">{"// ACCESS NODE"}</div><div className="section-head"><div><h2>FACTORX PROXY<br/><span>GENERATOR</span></h2><p>Configure. Gere. Copie.</p></div><div className="node-status"><span className="pulse"/> NODE READY</div></div><div className="generator-panel"><div className="filters"><Field label="LOCALIZAÇÃO"><select value={country} onChange={e=>setCountry(e.target.value)}><option value="">Todos os países</option>{status.countries.map(c=><option value={c.code} key={c.code}>{c.name||c.code} ({c.count})</option>)}</select></Field><Field label="PROTOCOLO"><div className="segmented">{["","HTTP","HTTPS","SOCKS4","SOCKS5"].map(p=><button className={protocol===p?"active":""} onClick={()=>setProtocol(p)} key={p||"ALL"}>{p||"ALL"}</button>)}</div></Field><Field label="QUANTIDADE"><div className="segmented">{[1,5,10,20,50].map(n=><button className={limit===String(n)?"active":""} onClick={()=>setLimit(String(n))} key={n}>{n}</button>)}</div></Field><Field label="QUALIDADE"><div className="segmented">{[["ALL","TODAS"],["GOOD","BOA"],["EXCELLENT","EXCELENTE"]].map(([v,l])=><button className={quality===v?"active":""} onClick={()=>setQuality(v)} key={v}>{l}</button>)}</div></Field><button className="button generate" onClick={generate} disabled={loading}>{loading?<><RefreshCw size={18} className="spin"/> ACESSANDO A REDE...</>:<>GERAR PROXYS <Zap size={18}/></>}</button></div>
      {(items.length>0||loading)&&<div className="results"><div className="results-head"><span>{items.length} PROXYS ENCONTRADAS <em>· FACTOR X // PROXYS</em></span><label><input type="checkbox" checked={withProtocol} onChange={e=>setWithProtocol(e.target.checked)}/> INCLUIR PROTOCOLO</label><button onClick={()=>copy(items.map(address).join("\n"),"all")}>{copied==="all"?<Check size={15}/>:<Copy size={15}/>} {copied==="all"?"COPIADO POR FACTOR X":"COPIAR TODAS"}</button></div>{items.map(p=><div className="proxy-row" key={p.id}><span className="flag">{p.countryCode||"--"}</span><code>{p.ip}:{p.port}</code><span>{p.protocol}</span><span>{p.latencyMs??"--"} MS</span><span className="online"><i/> {p.brVerified?"BR VERIFIED":"FX VERIFIED"}</span><button onClick={()=>copy(address(p),p.id)}>{copied===p.id?<Check size={15}/>:<Copy size={15}/>} {copied===p.id?"COPIADO":"COPIAR"}</button></div>)}</div>}
      {!loading&&loadError&&<div className="results"><p>{loadError}</p></div>}
      {!loading&&!loadError&&searched&&items.length===0&&<div className="results"><p>Nenhuma proxy ACTIVE corresponde aos filtros neste momento.</p></div>}
    </div></section>
    {copied&&<div className="copy-toast"><Check size={16}/><div><b>PROXY COPIADA</b><span>FACTOR X // PROXYS</span></div></div>}
    <section className="section network" id="network"><div className="section-tag">{"// LIVE INFRASTRUCTURE"}</div><div className="section-head"><div><h2>FACTORX <span>NETWORK</span></h2><p>Estoque monitorado. Reposição automática.</p></div><Activity className="orange"/></div><div className="network-grid"><div className="stock-card"><div className="card-label">PROXY STOCK</div><strong>{status.activeProxies}<small> / {status.targetStock}</small></strong><div className="progress"><i style={{width:`${Math.min(100,status.activeProxies/status.targetStock*100)}%`}}/></div><div className="card-row"><span>NETWORK STATUS</span><b className="online"><i/> {status.status}</b></div><div className="card-row"><span>ÚLTIMA VERIFICAÇÃO</span><b>{fmt(status.lastMaintenance)}</b></div><div className="card-row"><span>PRÓXIMA VERIFICAÇÃO</span><b>{fmt(status.nextMaintenance)}</b></div></div><div className="protocol-grid">{Object.entries(status.protocols).map(([p,n])=><div className="protocol-card" key={p}><Globe2/><b>{p.toUpperCase()}</b><strong>{n}</strong><span>ONLINE</span></div>)}</div></div></section>
    <section className="section how" id="how"><div className="section-tag">{"// AUTOMATED PIPELINE"}</div><h2>VOCÊ GERA.<br/><span>A FACTORX FAZ O RESTO.</span></h2><div className="steps">{[["01","COLETAMOS","Encontramos candidatas em fontes públicas."],["02","VERIFICAMOS","Cada proxy passa por uma requisição real."],["03","MANTEMOS","O estoque é revalidado a cada ciclo."],["04","REPOMOS","Buscamos somente o déficit necessário."]].map(([n,t,d])=><div className="step" key={n}><i>{n}</i><div className="step-icon">{n==="01"?<Globe2/>:n==="02"?<ShieldCheck/>:n==="03"?<Gauge/>:<RefreshCw/>}</div><h3>{t}</h3><p>{d}</p></div>)}</div><div className="terminal"><div className="terminal-top"><i/><i/><i/><span>factorx@network:~</span></div><code><b>&gt;</b> checking proxy stock...<br/><b>&gt;</b> active: <em>{status.activeProxies}</em><br/><b>&gt;</b> missing: <em>{Math.max(0,status.targetStock-status.activeProxies)}</em><br/><b>&gt;</b> validation cycle: 24h<br/><b>&gt;</b> network <em>{status.status.toLowerCase()}</em><span className="cursor">_</span></code></div></section>
    <footer><a className="brand" href="#top"><span>FACTOR</span><b>X</b></a><p>Proxy Infrastructure</p><div><a href="#network">Status</a><a href="/terms">Termos</a><a href="/privacy">Privacidade</a></div><small>As proxies são públicas e provenientes de fontes abertas. Disponibilidade, desempenho e segurança podem variar. Evite transmitir informações sensíveis através de proxies públicas.</small></footer>
  </main>;
}
function Stat({value,label}:{value:string;label:string}){return <div><strong>{value}</strong><span>{label}</span></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
